package com.inventory.inventoryservice.security.model;

public enum UserRoleEnum{
  ROLE_ADMIN,

  ROLE_BRAND_CREATE,
  ROLE_BRAND_GET,
  ROLE_BRAND_UPDATE,
  ROLE_BRAND_DELETE,
  ROLE_BRAND_SEARCH,

  ROLE_CATEGORY_CREATE,
  ROLE_CATEGORY_GET,
  ROLE_CATEGORY_UPDATE,
  ROLE_CATEGORY_DELETE,
  ROLE_CATEGORY_SEARCH,

  ROLE_PRODUCT_CREATE, // GROUP -> CREATE -> ROLE_BRAND_CREATE, ROLE_PRODUCT_CREATE
  ROLE_PRODUCT_GET,
  ROLE_PRODUCT_UPDATE,
  ROLE_PRODUCT_DELETE,
  ROLE_PRODUCT_SEARCH,


}
