
### AuthController::authenticate
POST http://localhost:8099/authenticate
Content-Type: application/json

{
  "username": "admin",
  "password": "092624"
}


### AuthController::authenticate
POST http://localhost:8099/authenticate
Content-Type: application/json

{
  "username": "s@gmail.com",
  "password": "123456"
}

> {% client.global.set("token", response.body.token);
    client.global.set("authority", response.body.token);  %}