

### BrandController::saveBrand
POST http://localhost:8099/api/v1/brands
Content-Type: application/json
Accept: application/json

{
  "brandName": "Brand3",
  "enabled": false
}

### BrandController::updateBrand
PUT http://localhost:8099/api/v1/brands/1
Content-Type: application/json
Accept: application/json

{
  "brandName": "Square2",
  "enabled": true
}

### BrandController::deleteBrand
DELETE http://localhost:8099/api/v1/brands/1
Content-Type: application/json
Accept: application/json

{
  "brandName": "Square2",
  "enabled": true
}

###
GET http://localhost:8099/api/v1/brands?name=mahadi&age=87
Accept: application/json

### BrandController::searchPage
POST http://localhost:8099/api/v1/brands/search-page
Content-Type: application/json
Accept: application/json

{
  "brandName": "Brand3",
  "enabled": false
}


### BrandController::searchList
POST http://localhost:8099/api/v1/brands/search-list
Content-Type: application/json
Accept: application/json

{
  "brandName": "Brand3",
  "enabled": false
}