### BrandController::saveBrand
POST http://localhost:8099/api/v1/brands
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "brandName": "iPhone-1"
}

### BrandController::getBrandById
GET http://localhost:8099/api/v1/brands/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### BrandController::updateBrand
PUT http://localhost:8099/api/v1/brands/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "brandName": "Square",
  "enabled": false
}


### BrandController::getAllBrand
GET http://localhost:8099/api/v1/brands
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


### BrandController::deleteBrand
DELETE http://localhost:8099/api/v1/brands/8
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


###
GET http://localhost:8099/api/v1/brands?name=mahadi&age=87
Accept: application/json
Authorization: Bearer {{token}}

### BrandController::searchPage
POST http://localhost:8099/api/v1/brands/search-page
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "brandName": "Brand3",
  "enabled": false
}


### BrandController::searchList
POST http://localhost:8099/api/v1/brands/search-list
Content-Type: application/json
Accept: application/json

{
  "brandName": "Brand3",
  "enabled": false
}