### CategoryController::saveCategory
POST http://localhost:8099/api/v1/categorys
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "categoryName": "Category-7"
}


### CategoryController::getAllCategory
GET http://localhost:8099/api/v1/categorys
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### CategoryController::getCategoryById
GET http://localhost:8099/api/v1/categorys/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


### CategoryController::updateCategory
PUT http://localhost:8099/api/v1/categorys/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "categoryName": "Good",
  "enabled": true
}

### CategoryController::deleteCategory
DELETE http://localhost:8099/api/v1/categorys/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "categoryName": "Square2",
  "enabled": true
}




### CategoryController::searchPage
POST http://localhost:8099/api/v1/categorys/search-page
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "categoryName": "Category1",
  "enabled": true
}

### CategoryController::searchList
POST http://localhost:8099/api/v1/categorys/search-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "categoryName": "Category1",
  "enabled": true
}
