

### CategoryController::saveCategory
POST http://localhost:8099/api/v1/categorys
Content-Type: application/json
Accept: application/json

{
  "categoryName": "Category1",
  "enabled": true
}

### CategoryController::updateCategory
PUT http://localhost:8099/api/v1/categorys/1
Content-Type: application/json
Accept: application/json

{
  "categoryName": "Good",
  "enabled": true
}

### CategoryController::deleteCategory
DELETE http://localhost:8099/api/v1/categorys/1
Content-Type: application/json
Accept: application/json

{
  "categoryName": "Square2",
  "enabled": true
}




### CategoryController::searchPage
POST http://localhost:8099/api/v1/categorys/search-page
Content-Type: application/json
Accept: application/json

{
  "categoryName": "Category1",
  "enabled": true
}


### CategoryController::searchList
POST http://localhost:8099/api/v1/categorys/search-list
Content-Type: application/json
Accept: application/json

{
  "categoryName": "Category1",
  "enabled": true
}
