

### CustomerController::saveCustomer
POST http://localhost:8099/api/v1/customers
Content-Type: application/json
Accept: application/json

{
  "customerName":"Sazib Khan",
  "phoneNumber":"01717226385",
  "customerType":"Nice",
  "email":"Square",
  "customerImage":"Picture",
  "enabled": true
}



### CustomerController::updateCustomer
PUT http://localhost:8099/api/v1/customers/1
Content-Type: application/json
Accept: application/json

{
  "customerName":"Sazib Khan",
  "phoneNumber":"01717226385",
  "customerType":"Nice",
  "email":"Square",
  "customerImage":"Picture",
  "enabled": true
}

### CustomerController::deleteCustomer
DELETE http://localhost:8099/api/v1/customers/1
Content-Type: application/json
Accept: application/json

