
### PurchaseController::savePurchase
POST http://localhost:8099/api/v1/purchases
Content-Type: application/json
Accept: application/json

{
  "purchaseDate":"2023-08-21",
  "supplierId": 1,
  "enabled": true,
  "items": [
    {
      "productId": 2,
      "purchasePrice": 12.0,
      "salesPrice": 15.0
    }
  ]
}






### PurchaseController::savePurchase
POST http://localhost:8099/api/v1/purchases/search-page
Content-Type: application/json
Accept: application/json

{
  "salesDate":"2023-08-21"
}


### PurchaseController::savePurchase
POST http://localhost:8099/api/v1/purchases/search-list
Content-Type: application/json
Accept: application/json

{
  "salesDate":"2023-08-21"
}
