### ReconciliationController::saveReconciliation
POST http://localhost:8099/api/v1/reconciliations
Content-Type: application/json
Accept: application/json
{
  "reconciliationDate": "2024-03-29",
  "items": [
    {
      "productId": 1,
      "reconciliationType": "WRITE_OFF",
      "quantity": 10.0
    },
    {
      "productId": 2,
      "reconciliationType": "WRITE_ON",
      "quantity": 10.0
    }
  ]
}

### ReconciliationController::approveReconciliation
PUT http://localhost:8099/api/v1/reconciliations/approve/2
Content-Type: application/json
Accept: application/json
{
  "reconciliationStatus": "Approved"
}