### ReconciliationController::saveReconciliation
POST http://localhost:8099/api/v1/reconciliations
Content-Type: application/json
Accept: application/json

{
   "reconciliationDate":"2024-03-24",
   "status": true,
   "enabled": false,
  "items": [
    {
      "productId": 1,
       "quantity":10.0,
      "purchasePrice": 12.0,
      "salesPrice": 15.0
    },
     {
      "productId": 2,
       "quantity":10.0,
      "purchasePrice": 12.0,
      "salesPrice": 15.0
    }
  ]
}