### StockController::saveStock
POST http://localhost:8099/api/v1/stocks
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "currentStock": 288,
    "productId": 1,
    "enabled": true
}
