### SupplierController::saveSupplier
POST http://localhost:8099/api/v1/suppliers
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "supplierName": "Square",
  "supplierAddress": "sazib@gmail.com",
  "phoneNumber": "01717226385"
}

### SupplierController::updateSupplier
PUT http://localhost:8099/api/v1/suppliers/10
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "supplierName": "Square",
  "supplierAddress": "sazib@gmail.com",
  "phoneNumber": "01717226385",
  "enabled": true
}

### SupplierController::deleteSupplier
DELETE http://localhost:8099/api/v1/suppliers/9
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


### SupplierController::searchPage
POST http://localhost:8099/api/v1/suppliers/search-page
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "supplierName": "Square",
  "supplierAddress": "sazib@gmail.com",
  "phoneNumber": "01717226385",
  "enabled": true
}

### SupplierController::searchList
POST http://localhost:8099/api/v1/suppliers/search-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "supplierName": "Square",
  "supplierAddress": "sazib@gmail.com",
  "phoneNumber": "Square",
  "enabled": true
}