### UserController::saveUser
POST http://localhost:8099/api/v1/users/create-user
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "fullName": "Sazib Khan-1",
  "username": "sazib2",
  "password": "123456",
  "authority": "USER",
  "roles": [
    {
      "roleName": "ROLE_CATAGORY_CREATE"
    },
    {
      "roleName": "ROLE_CATAGORY_CREATE"
    },
    {
      "roleName": "ROLE_CATAGORY_UPDATE"
    }
  ],
  "enabled": true
}




### UserController::saveUser
POST http://localhost:8099/api/v1/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "fullName":"Sazib Khan",
  "username": "sazib1",
  "password":"123456",
  "authority":"auth",
  "enabled": true
}

### UserController::updateUser
PUT  http://localhost:8099/api/v1/users/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


{
  "fullName":"Sazib Khan",
  "username": "sazib@gmail.com",
  "password":"abc12",
  "authority":"auth",
  "enabled": true
}

### UserController::deleteUser
DELETE  http://localhost:8099/api/v1/users/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


### UserController::searchPage
POST http://localhost:8099/api/v1/users/search-page
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "fullName":"Sazib Khan",
  "username": "sazib@gmail.com",
  "password":"abc12",
  "authority":"auth",
  "enabled": true
}

### UserController::searchList
POST http://localhost:8099/api/v1/users/search-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "fullName":"Sazib Khan",
  "username": "sazib@gmail.com",
  "password":"abc12",
  "authority":"auth",
  "enabled": true
}
